### ISSUE TITLE
Das Spiel crashed

### ISSUE THREAD

**Issue by TiToMoskito** [copymark/TM-Trainer#6]
Wenn ich builde und versuche das Spiel zu starten, dann crashed das Game.
Habe aber keine Fehlermeldung vom Injector.

**Comment by mark-engerisser** [comment]
mmhh erstellst du im DEBUG modus?

**Comment by Rexima** [comment]
Ich habe mal in DEBUG und RELEASE Modus gebuilded.

**Comment by Rexima** [comment]
Ok, mein Fehler... Habe vergessen, die komplette Projektmappe zu compilen.
