### ISSUE TITLE
Fehler beim kompilieren

### ISSUE THREAD

**Issue by eschlenzka** [copymark/TM-Trainer#9]
Fehler  1   error RC1015: cannot open include file 'afxres.h'.  E:\Downloads\TM-Trainer-master\TM-Trainer-master\tlTrainer\tlTrainer.rc 10  1   tlTrainer
Fehler  2   error RC1015: cannot open include file 'afxres.h'.  E:\Downloads\TM-Trainer-master\TM-Trainer-master\TM_Trainer\TM_Trainer.rc   10  1   TMUF_Trainer

**Comment by copymark** [comment]
Fixed
